### ISSUE TITLE
how to train equivariant encoder

### ISSUE THREAD

**Issue by chenzhu01** [IIT-PAVIS/DiffAssemble#2]
Thanks for your great work! But I can't find a pre-trained equivariant encoder mentioned in the paper. And it seems that its weights are not frozen during the training phase (i run puzzle_diff\train_3d.py). Can you provide more detail about how to train this encoder?

**Comment by gianscarpe** [comment]
Hi and thanks for your interest in our work! That's expected, we don't pre-train the equivariant encoder but rather train it from scratch along with the despiser
