### ISSUE TITLE
Missing model.backbones.backbone_vist

### ISSUE THREAD

**Issue by aplesner** [IIT-PAVIS/DiffAssemble#6]
Hi,
I am trying to run the code, but there are issues with the backbones directory. There is no model.backbones.backbone_vist, so the import statement attached below fails.

https://github.com/IIT-PAVIS/DiffAssemble/blob/256df64d4e5465e690b5b84e6024c60e21c3f3c8/puzzle_diff/model/backbones/__init__.py#L1

**Comment by gianscarpe** [comment]
HI! You can safely remove that line, it's not part of the published code
